version: "3.7"

services:
  reverse-proxy:
    image: reverse-proxy
    container_name: nginx-proxy
    build:
      context: .
    depends_on:
      - nodejs
      - golang
    volumes:
      - "./docker-deps/default.conf:/etc/nginx/conf.d/default.conf"
    restart: "always"
    ports:
      - 80:80

  nodejs:
    image: bootcamp-node
    container_name: node-bootcamp
    build:
      context: ../hello-world-nodejs/
    ports:
      - 3000:3000
    restart: on-failure

  golang:
    image: bottcamp-go
    container_name: golang-bootcamp
    build:
      context: ../hello-world-golang/
    ports:
      - 3002:3002
    restart: on-failure
